[build]
  command = "pnpm build"
  publish = "dist"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/terms"
  to = "/terms-of-service"
  status = 301

[[redirects]]
  from = "/privacy"
  to = "/privacy-policy"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
